#!/bin/bash
if [[ $# -lt 1 ]] || [[ ! -d $1   ]]; then
        echo "Usage:
        $0 ~/pictures/wallpapers/nsfw"
        exit 1
fi

export SWWW_TRANSITION_FPS=60
export SWWW_TRANSITION_STEP=255
export SWWW_TRANSITION=fade

INTERVAL=30

while true; do
        find "$1" \
                | while read -r img; do
                        echo "$((RANDOM % 17960)):$img"
                done \
                | sort -n | cut -d':' -f2- \
                | while read -r img; do
        if [[ "$img" != "$1" ]]; then
                swww img "$img"
                sleep $INTERVAL
        fi
        done
done
